/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.CSAAT.greet;

public class Greet {

    public Greet() {
    }

    public String hello(String name) {
        return "Hello " + name;
    }

}
